# Generated by Django 4.2.30 on 2026-04-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Prestado', 'Prestado'), ('En mantención', 'En mantención')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='estado_prestamo',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Devuelto', 'Devuelto'), ('Atrasado', 'Atrasado')], max_length=20),
        ),
    ]
