# Generated by Django 4.2.30 on 2026-04-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_rol_options_alter_herramienta_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='estado_prestamo',
            field=models.CharField(choices=[('Prestado', 'Prestado'), ('Devuelto', 'Devuelto')], max_length=20),
        ),
    ]
